apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaffold.fullname" $ }}-backend
  labels:
    app: {{ include "scaffold.fullname" $ }}-backend
    {{- include "scaffold.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: {{ .Values.backend.port | quote }}
  selector:
    app: {{ include "scaffold.fullname" $ }}-backend
