apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scaffold.fullname" . }}-backend-secret
  labels:
    app: {{ template "scaffold.fullname" . }}-backend
    {{- include "scaffold.labels" . | nindent 4 }}
type: Opaque
data:
    AUTH0_CLIENT_SECRET: {{ $.Values.backend.auth0.clientSecret | trim | b64enc | quote }}
    DATABASE_URI: {{ .Values.backend.db.uri | b64enc | quote }}
    CELERY_BROKER_URL: {{ .Values.celery.brokerURL | b64enc | quote }}
    CELERY_RESULT_BACKEND: {{ include "scaffold.celery.backendURL" . | b64enc | quote }}
    FLASK_SECRET_KEY: {{ .Values.backend.secretKey | b64enc | quote }}
