apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scaffold.fullname" . }}-flower-secret
  labels:
    app: {{ template "scaffold.fullname" . }}-flower
    {{- include "scaffold.labels" . | nindent 4 }}
type: Opaque
data:
    CELERY_BROKER_URL: {{ .Values.celery.brokerURL | b64enc | quote }}
    CELERY_RESULT_BACKEND: {{ include "scaffold.celery.backendURL" . | b64enc | quote }}

